### ISSUE TITLE
Protect when there's no keys in Vartype.schema

### ISSUE THREAD

**Issue by lekosfmi** [iotile/ng-iotile-cloud#109]
<img width="885" alt="screen shot 2018-03-22 at 5 39 55 pm" src="https://user-images.githubusercontent.com/10788981/37805517-19d8a0e4-2df8-11e8-9cbe-4e2bf02139dd.png">

**Comment by dkarchmer** [comment]
Which schema is missing?

**Comment by lekosfmi** [comment]
This is related to #636 and also #641

**Comment by lekosfmi** [comment]
The schema looks similar to this testing file https://github.com/iotile/ng-iotile-cloud/blob/master/tests/models/vartype.spec.ts#L59

**Comment by dkarchmer** [comment]
Which variable type?

**Comment by lekosfmi** [comment]
I believe its the default that doesnt have the `schema` that is causing the error. https://iotile.cloud/api/v1/vartype/default/

**Comment by dkarchmer** [comment]
Which stream has this VarType. We need to understand if we need to better configure the SG or what. Otherwise, how exactly are you going to protect? Other than giving a nice error to the user saying the SG is misconfigured?

**Comment by lekosfmi** [comment]
It is this stream: https://iotile.cloud/api/v1/event/?filter=s--0000-00ec--0000-0000-0000-04e6--5020 that has the [default VarType](https://iotile.cloud/api/v1/vartype/default/).
