### ISSUE TITLE
Add class to store IOTile Variable Constants

### ISSUE THREAD

**Issue by dkarchmer** [iotile/ng-iotile-cloud#90]
There is a number of stream variables that are hardcoded on any application interacting with IOTile Cloud. For example, 
  - Gateway Scan Begin: `5a00`
  - Gateway Scan End: `5a01`
  - Gateway Scan Failure: `5a03`
  - End of Trip Summary: `5a07`
  etc.

Let's add a proper set of constants for clients to avoid hard coding these stream variable IDs

**Comment by dkarchmer** [comment]
Maybe just add a class like:

export const  IOTileSysVar {
    gatewayScanBegin: '5a00',
    gatewayScanEnd: '5a01',
    etc.
}

**Comment by lekosfmi** [comment]
The class `IOTileSysVar` can be access like `this._cloud.IOTileSysVar`? Or, should it be it's own standalone classes?

**Comment by dkarchmer** [comment]
There is no dependency on the cloud, so there is no need to access via cloud. It should be global or under model.
